#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER AVR_GCC
// #define DISABLE_OS

#define SERIAL_PORT UART3_PORT
#define UART3_AT_B4_B5_ENABLE
#define SERIAL_ENABLE
#define SERIAL_LINE_ENABLE
#define SERIAL_TX_INTERRUPT_ENABLE
// #define SERIAL_TX_BUFFER_CONF 128

#define DEBUG_LEVEL_CONF DEBUG_TEXT_WITH_TIME
// #define TASK_HAS_STRING_NAMES_CONF

// #define MEGA4809_DEBUG_LEVEL_CONF MEGA4809_DEBUG_LEVEL3
// #define CLOCK_DEBUG_LEVEL_CONF CLOCK_DEBUG_LEVEL2
// #define PTIMER_DEBUG_LEVEL_CONF	PTIMER_DEBUG_LEVEL3
// #define TASK_DEBUG_LEVEL_CONF TASK_DEBUG_LEVEL3


#endif

