#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER AVR_GCC
#define SERIAL_ENABLE

/*
#define DEBUG_LEVEL_CONF DEBUG_TEXT_WITH_TIME
#define MEGA4809_DEBUG_LEVEL_CONF MEGA4809_DEBUG_LEVEL3
#define CLOCK_DEBUG_LEVEL_CONF CLOCK_DEBUG_LEVEL2
#define PTIMER_DEBUG_LEVEL_CONF	PTIMER_DEBUG_LEVEL3
#define TASK_DEBUG_LEVEL_CONF TASK_DEBUG_LEVEL3
#define TASK_HAS_STRING_NAMES_CONF
*/

#endif

