#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER AVR_STUDIO
#define SERIAL_ENABLE
#define DEBUG_LEVEL_CONF DEBUG_TEXT_WITH_TIME
#define PROCESS_HAS_STRING_NAMES_CONF
//#define PROCESS_DEBUG_LEVEL_CONF PROCESS_DEBUG_LEVEL3
//#define PTIMER_DEBUG_LEVEL_CONF PTIMER_DEBUG_LEVEL3
//#define CLOCK_DEBUG_LEVEL_CONF CLOCK_DEBUG_LEVEL3

#endif

