#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER AVR_GCC
#define DEBUG_LEVEL_CONF DEBUG_TEXT_WITH_TIME
//#define TASK_DEBUG_LEVEL_CONF TASK_DEBUG_LEVEL3
//#define PTIMER_DEBUG_LEVEL_CONF PTIMER_DEBUG_LEVEL3
//#define CLOCK_DEBUG_LEVEL_CONF CLOCK_DEBUG_LEVEL2
//#define MEGA328P_DEBUG_LEVEL_CONF MEGA328P_DEBUG_LEVEL3

#define SERIAL_ENABLE
#define TASK_HAS_STRING_NAMES_CONF
//#define SERIAL_TX_INTERRUPT_ENABLE

// Serial Tx interrupt not working properly

//#define SERIAL_TX_INTERRUPT_ENABLE
//#define SERIAL_TX_BUFFER_CONF 512



#endif

