#ifndef CONFIG_H
#define CONFIG_H

#define COMPILER AVR_GCC
#define DEBUG_LEVEL_CONF DEBUG_TEXT_WITH_TIME
//#define CLOCK_DEBUG_LEVEL_CONF CLOCK_DEBUG_LEVEL2
//#define PTIMER_DEBUG_LEVEL_CONF PTIMER_DEBUG_LEVEL3
#define MEGA16_DEBUG_LEVEL_CONF MEGA16_DEBUG_LEVEL3
#define SERIAL_ENABLE
#define OS_TIMER_TYPE_CONF TIMER_1
#define TASK_HAS_STRING_NAMES_CONF

#endif

